# Initial timer duration (in ticks, 240 = 12 seconds)
start-timer: 240.0
# Collections â€“ flexible system
collections:
  doors:
    name: "Doors"
    type: progressive
    items:
      - OAK_DOOR
      - SPRUCE_DOOR
      - BIRCH_DOOR
      - JUNGLE_DOOR
      - ACACIA_DOOR
      - DARK_OAK_DOOR
      - CRIMSON_DOOR
      - WARPED_DOOR
      - MANGROVE_DOOR
      - BAMBOO_DOOR
      - IRON_DOOR
      - CHERRY_DOOR
      - "COPPER_DOOR|WAXED_COPPER_DOOR|EXPOSED_COPPER_DOOR|WAXEDEXPOSED_COPPER_DOOR|WEATHERED_COPPER_DOOR|WAXEDWEATHERED_COPPER_DOOR|OXIDIZED_COPPER_DOOR|WAXED_OXIDIZED_COPPER_DOOR"
      - PALE_OAK_DOOR
    scores:
      - 1
      - 5
      - 10
      - 15
      - 25
      - 50
      - 75
      - 100
      - 150
      - 250
      - 450
      - 800
      - 1200
      - 1800  # Still 14 slots total (scores match item count)

  workstations:
    name: "Workstations"
    type: complete
    items:
      - BLAST_FURNACE
      - SMOKER
      - CARTOGRAPHY_TABLE
      - BREWING_STAND
      - COMPOSTER
      - BARREL
      - FLETCHING_TABLE
      - CAULDRON
      - LECTERN
      - STONECUTTER
      - LOOM
      - SMITHING_TABLE
      - GRINDSTONE
    bonus: 350

  dyes:
    name: "Dyes"
    type: complete
    items:
      - WHITE_DYE
      - LIGHT_GRAY_DYE
      - GRAY_DYE
      - BLACK_DYE
      - BROWN_DYE
      - RED_DYE
      - ORANGE_DYE
      - YELLOW_DYE
      - LIME_DYE
      - GREEN_DYE
      - CYAN_DYE
      - LIGHT_BLUE_DYE
      - BLUE_DYE
      - PURPLE_DYE
      - MAGENTA_DYE
      - PINK_DYE
    bonus: 400

  buckets:
    name: "Buckets"
    type: progressive
    items:
      - BUCKET
      - WATER_BUCKET
      - LAVA_BUCKET
      - MILK_BUCKET
      - COD_BUCKET
      - SALMON_BUCKET
      - PUFFERFISH_BUCKET
      - TROPICAL_FISH_BUCKET
      - AXOLOTL_BUCKET
      - POWDER_SNOW_BUCKET
    scores:
      - 5
      - 10
      - 15
      - 30
      - 50
      - 100
      - 250
      - 400
      - 750
      - 1300

  soups:
    name: "Soups"
    type: complete
    items:
      - MUSHROOM_STEW
      - RABBIT_STEW
      - SUSPICIOUS_STEW
      - BEETROOT_SOUP
    bonus: 200

  brewing-ingredients:
    name: "Brewing Ingredients"
    type: progressive
    items:
      - REDSTONE
      - STONE
      - SUGAR
      - GUNPOWDER
      - SPIDER_EYE
      - GOLDEN_CARROT
      - BREEZE_ROD
      - FERMENTED_SPIDER_EYE
      - COBWEB
      - GHAST_TEAR
      - BLAZE_POWDER
      - NETHER_WART
      - GLOWSTONE_DUST
      - MAGMA_CREAM
      - GLISTERING_MELON_SLICE
      - PUFFERFISH
      - RABBIT_FOOT
      - SLIME_BLOCK
      - DRAGON_BREATH
      - PHANTOM_MEMBRANE
    scores:
      - 5
      - 10
      - 15
      - 20
      - 30
      - 50
      - 75
      - 100
      - 150
      - 200
      - 350
      - 500
      - 650
      - 800
      - 100
      - 1250
      - 1500
      - 2000
      - 2500
      - 3000

# Shulker box colors for starting items (use valid Minecraft 1.21.11 material names)
shulker-colors:
  - RED_SHULKER_BOX
  - PURPLE_SHULKER_BOX

# Item values for Loot Hunt scoring
item-values:
  ACACIA_HANGING_SIGN: 0.4
  ACTIVATOR_RAIL: 1.1
  AMETHYST_CLUSTER: 25
  AMETHYST_SHARD: 2
  ANCIENT_DEBRIS: 20
  ANGLER_POTTERY_SHERD: 60
  ANVIL: 31
  ARCHER_POTTERY_SHERD: 60
  ARMS_UP_POTTERY_SHERD: 60
  ARROW: 0.5
  AXOLOTL_BUCKET: 3
  BAMBOO_HANGING_SIGN: 0.4
  BEE_NEST: 60
  BELL: 25
  BIRCH_HANGING_SIGN: 0.4
  BLADE_POTTERY_SHERD: 60
  BLAST_FURNACE: 5
  BLAZE_POWDER: 4
  BLAZE_ROD: 8
  BOLT_ARMOR_TRIM_SMITHING_TEMPLATE: 70
  BOOK: 0.8
  BOOKSHELF: 2.4
  BREEZE_ROD: 4
  BREWER_POTTERY_SHERD: 60
  BREWING_STAND: 8
  BRUSH: 2.1
  BUCKET: 3
  BURN_POTTERY_SHERD: 60
  CAKE: 10
  CAULDRON: 7
  CHAINMAIL_BOOTS: 10
  CHAINMAIL_CHESTPLATE: 30
  CHAINMAIL_HELMET: 10
  CHAINMAIL_LEGGINGS: 25
  CHERRY_HANGING_SIGN: 0.4
  CHEST_MINECART: 5
  CHIPPED_ANVIL: 31
  CLOCK: 8.7
  COAL: 0.1
  COAL_BLOCK: 0.9
  COAL_ORE: 1
  COAST_ARMOR_TRIM_SMITHING_TEMPLATE: 70
  COD_BUCKET: 3
  COMPASS: 4.7
  COPPER_AXE: 0.3
  COPPER_BLOCK: 0.9
  COPPER_BOOTS: 0.4
  COPPER_CHESTPLATE: 0.8
  COPPER_HELMET: 0.5
  COPPER_HOE: 0.2
  COPPER_HORSE_ARMOR: 15
  COPPER_INGOT: 0.1
  COPPER_LEGGINGS: 0.7
  COPPER_NAUTILUS_ARMOR: 5
  COPPER_ORE: 2
  COPPER_PICKAXE: 0.3
  COPPER_SHOVEL: 0.1
  COPPER_SPEAR: 0.1
  COPPER_SWORD: 0.2
  CREAKING_HEART: 10
  CREEPER_HEAD: 300
  CRIMSON_HANGING_SIGN: 0.4
  CROSSBOW: 1.5
  CRYING_OBSIDIAN: 2.5
  DAMAGED_ANVIL: 31
  DANGER_POTTERY_SHERD: 60
  DARK_OAK_HANGING_SIGN: 0.4
  DEEPSLATE_COAL_ORE: 50
  DEEPSLATE_COPPER_ORE: 3
  DEEPSLATE_DIAMOND_ORE: 18
  DEEPSLATE_EMERALD_ORE: 500
  DEEPSLATE_GOLD_ORE: 2
  DEEPSLATE_IRON_ORE: 2
  DEEPSLATE_LAPIS_ORE: 7
  DEEPSLATE_REDSTONE_ORE: 2
  DETECTOR_RAIL: 1.1
  DIAMOND: 10
  DIAMOND_AXE: 30
  DIAMOND_BLOCK: 90
  DIAMOND_BOOTS: 40
  DIAMOND_CHESTPLATE: 80
  DIAMOND_HELMET: 50
  DIAMOND_HOE: 0
  DIAMOND_HORSE_ARMOR: 25
  DIAMOND_LEGGINGS: 35
  DIAMOND_NAUTILUS_ARMOR: 70
  DIAMOND_ORE: 100
  DIAMOND_PICKAXE: 30
  DIAMOND_SHOVEL: 10
  DIAMOND_SPEAR: 10
  DIAMOND_SWORD: 20
  DRAGON_EGG: 500
  DRAGON_HEAD: 100
  DRIED_GHAST: 20
  DUNE_ARMOR_TRIM_SMITHING_TEMPLATE: 80
  ELYTRA: 250
  EMERALD: 5
  EMERALD_BLOCK: 45
  EMERALD_ORE: 50
  ENCHANTED_BOOK: 1
  ENCHANTED_GOLDEN_APPLE: 50
  ENCHANTING_TABLE: 32.8
  END_ROD: 2
  ENDER_CHEST: 38
  ENDER_EYE: 14
  ENDER_PEARL: 10
  EXPERIENCE_BOTTLE: 5
  EXPLORER_POTTERY_SHERD: 60
  EYE_ARMOR_TRIM_SMITHING_TEMPLATE: 70
  FEATHER: 2
  FILLED_MAP: 4.7
  FIRE_CHARGE: 1.7
  FLINT_AND_STEEL: 1
  FLOW_ARMOR_TRIM_SMITHING_TEMPLATE: 90
  FLOW_BANNER_PATTERN: 25
  FLOW_POTTERY_SHERD: 45
  FRIEND_POTTERY_SHERD: 60
  FURNACE_MINECART: 5
  GILDED_BLACKSTONE: 1
  GLISTERING_MELON_SLICE: 2.4
  GLOWSTONE: 4
  GLOWSTONE_DUST: 1
  GOAT_HORN: 100
  GOLD_BLOCK: 18
  GOLD_INGOT: 2
  GOLD_NUGGET: 0.2
  GOLD_ORE: 4
  GOLDEN_APPLE: 24
  GOLDEN_AXE: 6
  GOLDEN_BOOTS: 8
  GOLDEN_CARROT: 2.4
  GOLDEN_CHESTPLATE: 16
  GOLDEN_HELMET: 10
  GOLDEN_HOE: 4
  GOLDEN_HORSE_ARMOR: 25
  GOLDEN_LEGGINGS: 14
  GOLDEN_NAUTILUS_ARMOR: 20
  GOLDEN_PICKAXE: 6
  GOLDEN_SHOVEL: 2
  GOLDEN_SPEAR: 2
  GOLDEN_SWORD: 4
  GUNPOWDER: 1
  GUSTER_BANNER_PATTERN: 20
  GUSTER_POTTERY_SHERD: 45
  HEART_OF_THE_SEA: 15
  HEART_POTTERY_SHERD: 60
  HEARTBREAK_POTTERY_SHERD: 60
  HEAVY_CORE: 500
  HONEY_BOTTLE: 7
  HONEYCOMB: 3
  HOPPER: 5
  HOPPER_MINECART: 10
  HOST_ARMOR_TRIM_SMITHING_TEMPLATE: 80
  HOWL_POTTERY_SHERD: 60
  IRON_AXE: 3
  IRON_BARS: 0.4
  IRON_BLOCK: 9
  IRON_BOOTS: 4
  IRON_CHAIN: 1.2
  IRON_CHESTPLATE: 8
  IRON_DOOR: 2
  IRON_HELMET: 5
  IRON_HOE: 2
  IRON_HORSE_ARMOR: 25
  IRON_INGOT: 1
  IRON_LEGGINGS: 7
  IRON_NAUTILUS_ARMOR: 10
  IRON_NUGGET: 0.1
  IRON_ORE: 2
  IRON_PICKAXE: 3
  IRON_SHOVEL: 1
  IRON_SPEAR: 1
  IRON_SWORD: 2
  JUNGLE_HANGING_SIGN: 0.4
  LANTERN: 0.8
  LAPIS_BLOCK: 4.5
  LAPIS_LAZULI: 0.5
  LAPIS_ORE: 7
  LARGE_AMETHYST_BUD: 20
  LARGE_FERN: 100
  LAVA_BUCKET: 3
  LEATHER: 2
  LEATHER_BOOTS: 4
  LEATHER_CHESTPLATE: 16
  LEATHER_HELMET: 10
  LEATHER_LEGGINGS: 14
  LECTERN: 2.4
  LIGHT_WEIGHTED_PRESSURE_PLATE: 4
  LODESTONE: 1
  MANGROVE_HANGING_SIGN: 0.4
  MAP: 4.7
  MEDIUM_AMETHYST_BUD: 15
  MILK_BUCKET: 3
  MINECART: 5
  MINER_POTTERY_SHERD: 60
  MOURNER_POTTERY_SHERD: 60
  MUSIC_DISC_11: 25
  MUSIC_DISC_13: 10
  MUSIC_DISC_5: 0
  MUSIC_DISC_BLOCKS: 25
  MUSIC_DISC_CAT: 10
  MUSIC_DISC_CHIRP: 25
  MUSIC_DISC_CREATOR: 35
  MUSIC_DISC_CREATOR_MUSIC_BOX: 35
  MUSIC_DISC_FAR: 25
  MUSIC_DISC_LAVA_CHICKEN: 200
  MUSIC_DISC_MALL: 25
  MUSIC_DISC_MELLOHI: 25
  MUSIC_DISC_OTHERSIDE: 10
  MUSIC_DISC_PIGSTEP: 30
  MUSIC_DISC_PRECIPICE: 35
  MUSIC_DISC_RELIC: 250
  MUSIC_DISC_STAL: 25
  MUSIC_DISC_STRAD: 25
  MUSIC_DISC_TEARS: 25
  MUSIC_DISC_WAIT: 25
  MUSIC_DISC_WARD: 25
  NAME_TAG: 0.1
  NAUTILUS_SHELL: 40
  NETHER_GOLD_ORE: 3
  NETHER_QUARTZ_ORE: 3
  NETHER_WART: 10
  NETHERITE_AXE: 200
  NETHERITE_BLOCK: 900
  NETHERITE_BOOTS: 210
  NETHERITE_CHESTPLATE: 250
  NETHERITE_HELMET: 220
  NETHERITE_HOE: 190
  NETHERITE_HORSE_ARMOR: 195
  NETHERITE_INGOT: 100
  NETHERITE_LEGGINGS: 240
  NETHERITE_NAUTILUS_ARMOR: 240
  NETHERITE_PICKAXE: 200
  NETHERITE_SCRAP: 20
  NETHERITE_SHOVEL: 180
  NETHERITE_SPEAR: 180
  NETHERITE_SWORD: 190
  NETHERITE_UPGRADE_SMITHING_TEMPLATE: 70
  OAK_HANGING_SIGN: 0.4
  OBSIDIAN: 3
  OMINOUS_BOTTLE: 20
  PALE_OAK_HANGING_SIGN: 0.4
  PIGLIN_BANNER_PATTERN: 20
  PIGLIN_HEAD: 300
  PLENTY_POTTERY_SHERD: 60
  POWDER_SNOW_BUCKET: 3
  POWERED_RAIL: 2.1
  PRISMARINE_CRYSTALS: 4
  PRISMARINE_SHARD: 2
  PRIZE_POTTERY_SHERD: 60
  PUFFERFISH_BUCKET: 3
  QUARTZ: 1
  QUARTZ_BLOCK: 4
  RAIL: 0.4
  RAISER_ARMOR_TRIM_SMITHING_TEMPLATE: 80
  RAW_COPPER: 0.3
  RAW_COPPER_BLOCK: 2.7
  RAW_GOLD: 2
  RAW_GOLD_BLOCK: 18
  RAW_IRON: 1
  RAW_IRON_BLOCK: 9
  RECOVERY_COMPASS: 0
  REDSTONE: 0.7
  REDSTONE_BLOCK: 6.3
  REDSTONE_ORE: 4
  RIB_ARMOR_TRIM_SMITHING_TEMPLATE: 90
  SADDLE: 7
  SALMON_BUCKET: 3
  SCRAPE_POTTERY_SHERD: 45
  SEA_LANTERN: 20
  SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE: 70
  SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE: 80
  SHEAF_POTTERY_SHERD: 60
  SHEARS: 2
  SHELTER_POTTERY_SHERD: 60
  SHIELD: 1
  SHULKER_SHELL: 5
  SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE: 0
  SKELETON_SKULL: 0
  SKULL_POTTERY_SHERD: 60
  SMALL_AMETHYST_BUD: 10
  SMITHING_TABLE: 2
  SNIFFER_EGG: 80
  SNORT_POTTERY_SHERD: 60
  SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE: 70
  SPECTRAL_ARROW: 1
  SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE: 70
  SPONGE: 5
  SPRUCE_HANGING_SIGN: 0.4
  STONECUTTER: 1
  SUSPICIOUS_GRAVEL: 20
  SUSPICIOUS_SAND: 20
  TADPOLE_BUCKET: 3
  TALL_GRASS: 50
  TIDE_ARMOR_TRIM_SMITHING_TEMPLATE: 90
  TIPPED_ARROW: 2
  TNT: 5
  TNT_MINECART: 10
  TORCH: 0
  TOTEM_OF_UNDYING: 200
  TRIDENT: 250
  TRIPWIRE_HOOK: 0.5
  TROPICAL_FISH_BUCKET: 3
  TURTLE_EGG: 40
  VEX_ARMOR_TRIM_SMITHING_TEMPLATE: 70
  WARD_ARMOR_TRIM_SMITHING_TEMPLATE: 0
  WARPED_HANGING_SIGN: 0.4
  WATER_BUCKET: 3
  WAXED_COPPER_BLOCK: 0.9
  WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE: 80
  WET_SPONGE: 5
  WILD_ARMOR_TRIM_SMITHING_TEMPLATE: 80
  WIND_CHARGE: 1
  WITHER_SKELETON_SKULL: 300
  ZOMBIE_HEAD: 300


# Kill and death points
pvp:
  base-kill-points: 50
  base-death-points: 50
  points-reduction-factor: 2

# Custom ender pearls to give at start
custom-pearls:
  - sbitem: 1
    custom-model-data: 1160001
    display-name: "Levitation Pearl"
    amount: 1
  - sbitem: 2
    custom-model-data: 1160002
    display-name: "Speed Pearl (3)"
    amount: 1
  - sbitem: 20
    custom-model-data: 1160020
    display-name: "Speed Pearl (20)"
    amount: 1
  - sbitem: 3
    custom-model-data: 1160003
    display-name: "Regeneration Pearl"
    amount: 1
  - sbitem: 4
    custom-model-data: 1160004
    display-name: "Jump Boost Pearl"
    amount: 1

# Enchantment scoring
enchantments:
  points-per-tier: 3
  special-enchantments:
    MENDING: 11.3
    FROST_WALKER: 11.3
    WIND_BURST: 100
    SWIFT_SNEAK: 0

# Potion values for Loot Hunt scoring
potion-values:
  # Regular potions
  WATER: 0
  THICK: 0
  MUNDANE: 0
  AWKWARD: 0
  REGENERATION: 20
  LONG_REGENERATION: 20
  STRONG_REGENERATION: 0
  SWIFTNESS: 5
  LONG_SWIFTNESS: 5
  STRONG_SWIFTNESS: 5
  FIRE_RESISTANCE: 5
  LONG_FIRE_RESISTANCE: 5
  POISON: 5
  LONG_POISON: 5
  STRONG_POISON: 5
  HEALING: 5
  STRONG_HEALING: 5
  NIGHT_VISION: 5
  LONG_NIGHT_VISION: 5
  WEAKNESS: 5
  LONG_WEAKNESS: 5
  STRENGTH: 5
  LONG_STRENGTH: 5
  STRONG_STRENGTH: 5
  SLOWNESS: 5
  LONG_SLOWNESS: 5
  STRONG_SLOWNESS: 5
  LEAPING: 5
  LONG_LEAPING: 5
  STRONG_LEAPING: 5
  HARMING: 5
  STRONG_HARMING: 5
  WATER_BREATHING: 10
  LONG_WATER_BREATHING: 10
  INVISIBILITY: 5
  LONG_INVISIBILITY: 5
  SLOW_FALLING: 5
  LONG_SLOW_FALLING: 5
  LUCK: 5
  TURTLE_MASTER: 5
  LONG_TURTLE_MASTER: 5
  STRONG_TURTLE_MASTER: 5
  WIND_CHARGED: 5
  WEAVING: 5
  OOZING: 5
  INFESTED: 5
  # Splash potions
  SPLASH_WATER: 0
  SPLASH_THICK: 0
  SPLASH_MUNDANE: 0
  SPLASH_AWKWARD: 0
  SPLASH_REGENERATION: 20
  SPLASH_LONG_REGENERATION: 20
  SPLASH_STRONG_REGENERATION: 0
  SPLASH_SWIFTNESS: 5
  SPLASH_LONG_SWIFTNESS: 5
  SPLASH_STRONG_SWIFTNESS: 5
  SPLASH_FIRE_RESISTANCE: 5
  SPLASH_LONG_FIRE_RESISTANCE: 5
  SPLASH_POISON: 5
  SPLASH_LONG_POISON: 5
  SPLASH_STRONG_POISON: 5
  SPLASH_HEALING: 5
  SPLASH_STRONG_HEALING: 5
  SPLASH_NIGHT_VISION: 5
  SPLASH_LONG_NIGHT_VISION: 5
  SPLASH_WEAKNESS: 5
  SPLASH_LONG_WEAKNESS: 5
  SPLASH_STRENGTH: 5
  SPLASH_LONG_STRENGTH: 5
  SPLASH_STRONG_STRENGTH: 5
  SPLASH_SLOWNESS: 5
  SPLASH_LONG_SLOWNESS: 5
  SPLASH_STRONG_SLOWNESS: 5
  SPLASH_LEAPING: 5
  SPLASH_LONG_LEAPING: 5
  SPLASH_STRONG_LEAPING: 5
  SPLASH_HARMING: 5
  SPLASH_STRONG_HARMING: 5
  SPLASH_WATER_BREATHING: 5
  SPLASH_LONG_WATER_BREATHING: 5
  SPLASH_INVISIBILITY: 5
  SPLASH_LONG_INVISIBILITY: 5
  SPLASH_SLOW_FALLING: 5
  SPLASH_LONG_SLOW_FALLING: 5
  SPLASH_LUCK: 5
  SPLASH_TURTLE_MASTER: 5
  SPLASH_LONG_TURTLE_MASTER: 5
  SPLASH_STRONG_TURTLE_MASTER: 5
  SPLASH_WIND_CHARGED: 5
  SPLASH_WEAVING: 5
  SPLASH_OOZING: 5
  SPLASH_INFESTED: 5
  # Lingering potions
  LINGERING_WATER: 0
  LINGERING_THICK: 0
  LINGERING_MUNDANE: 0
  LINGERING_AWKWARD: 0
  LINGERING_REGENERATION: 20
  LINGERING_LONG_REGENERATION: 20
  LINGERING_STRONG_REGENERATION: 0
  LINGERING_SWIFTNESS: 5
  LINGERING_LONG_SWIFTNESS: 5
  LINGERING_STRONG_SWIFTNESS: 5
  LINGERING_FIRE_RESISTANCE: 5
  LINGERING_LONG_FIRE_RESISTANCE: 5
  LINGERING_POISON: 5
  LINGERING_LONG_POISON: 5
  LINGERING_STRONG_POISON: 5
  LINGERING_HEALING: 5
  LINGERING_STRONG_HEALING: 5
  LINGERING_NIGHT_VISION: 5
  LINGERING_LONG_NIGHT_VISION: 5
  LINGERING_WEAKNESS: 5
  LINGERING_LONG_WEAKNESS: 5
  LINGERING_STRENGTH: 5
  LINGERING_LONG_STRENGTH: 5
  LINGERING_STRONG_STRENGTH: 5
  LINGERING_SLOWNESS: 5
  LINGERING_LONG_SLOWNESS: 5
  LINGERING_STRONG_SLOWNESS: 5
  LINGERING_LEAPING: 5
  LINGERING_LONG_LEAPING: 5
  LINGERING_STRONG_LEAPING: 5
  LINGERING_HARMING: 5
  LINGERING_STRONG_HARMING: 5
  LINGERING_WATER_BREATHING: 10
  LINGERING_LONG_WATER_BREATHING: 10
  LINGERING_INVISIBILITY: 5
  LINGERING_LONG_INVISIBILITY: 5
  LINGERING_SLOW_FALLING: 5
  LINGERING_LONG_SLOW_FALLING: 5
  LINGERING_LUCK: 5
  LINGERING_TURTLE_MASTER: 5
  LINGERING_LONG_TURTLE_MASTER: 5
  LINGERING_STRONG_TURTLE_MASTER: 5
  LINGERING_WIND_CHARGED: 5
  LINGERING_WEAVING: 5
  LINGERING_OOZING: 5
  LINGERING_INFESTED: 5